name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Rename build artifacts
        run: mv build/libs/FPS-Display*.jar build/libs/FDPClient_build.jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: FPS-Display Build
          path: build/libs/FPS-Display_build.jar
